---
name: Tag Release

on:
  release:
    types: [created]

jobs:
  tag:
    runs-on: ubuntu-24.04

    permissions:
      contents: write # Required for tag operation.

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0 # Fetch tag history.
          persist-credentials: false

      - name: Tag release version
        env:
          GH_TOKEN: ${{ github.token }}
          GH_TAG: ${{ github.event.release.tag_name}}
        run: |
          version=${GH_TAG%%.*}
          gh api /repos/${{ github.repository }}/git/refs/tags/${version} --method PATCH --silent --field sha="${GITHUB_SHA}" --field force=true || \
            gh api /repos/${{ github.repository }}/git/refs --method POST --silent --field sha="${GITHUB_SHA}" --field ref="refs/tags/${version}"
